### PR TITLE
Add a way to control when HTML report debug is gathered, and capture logs unless excluded

### PR DESCRIPTION
**Pull request by davehunt**
Also added a section to the documentation on the HTML report.

### CODE REVIEW

**Comment by davehunt** [comment]
@bobsilverberg would you mind reviewing this?

**Comment by davehunt** [comment]
I've merged this in https://github.com/davehunt/pytest-selenium/commit/768d0e41c520f60f4ee15c032b67ba015aca87b2 but would still appreciate a post-merge review if you have any feedback or suggestions.

**Comment by bobsilverberg** [comment]
@davehunt I just looked through the diff and it looks good to me. Nice additions. I notice there aren't any tests added for these changes. I assume you tested it all manually and were satisfied with that.

**Comment by davehunt** [comment]
Originally I didn't have tests because `pytest-html` wasn't a dependency. Now it is, I think it makes sense to add tests for the customisation, but I have yet to write these tests.

**Pull request closed without merging**
