### PR TITLE
Simplify fixture to return Selenium driver

### PR DESCRIPTION
**Pull request by davehunt**
Examples of use:
https://github.com/davehunt/mozwebqa-examples/tree/pytest-selenium
https://github.com/davehunt/Affiliates-Tests/tree/pytest-selenium

Pinging @bobsilverberg for review.

### CODE REVIEW

**Comment by davehunt** [comment]
I can replicate the test failure, but I don't think it's related to this patch - it looks like something has regressed when trying to find elements in the about:support page. I wonder if @AutomatedTester has seen this?

**Comment by davehunt** [comment]
Travis is happy now! :smile:

**Comment by davehunt** [comment]
This addresses issue #3

**Comment by bobsilverberg** [comment]
LGTM @davehunt. Pretty simple changes (mostly to tests) and all the tests pass locally for me (except for `test_missing_chrome_binary` and `test_proxy` (the Opera one) which always fail for me)).

r+

**Pull request merged**
