### PR TITLE
Added python3 and pypy to travis test suite

### PR DESCRIPTION
**Pull request by codingjoe**

### CODE REVIEW

**Comment by codingjoe** [comment]
@davehunt so far so good. This will at least provide everyone with some feedback when writing new code.
I couldn't figure out what the `cloud` package is all about? What is it and where do I get it in python3?

**Comment by davehunt** [comment]
The `cloud` package is here: https://github.com/davehunt/pytest-selenium/tree/master/pytest_selenium/cloud

**Comment by codingjoe** [comment]
@davehunt hahaha, yes, I found out myself. I'll fix the imports. Than we'll have more info on what needs attention.

**Comment by davehunt** [comment]
@codingjoe it looks like there's only a few failures, but Travis is timing out. Do you think we should keep working on this pull until we're passing for all versions?

**Comment by codingjoe** [comment]
@davehunt I'd just merge this for now. That will allow you got get an overview if a new feature is python3 ready or not. I'll continue working on fixed. But it might take a while.

I'll try to make time for it asap.

**Comment by davehunt** [comment]
Thanks @codingjoe!

**Pull request merged**
