### PR TITLE
Reimplement drivers as fixtures and introduce hooks for extending the HTML report

### PR DESCRIPTION
**Pull request by davehunt**
I think this is ready for review, @bobsilverberg!

### CODE REVIEW

**Comment by bobsilverberg** [comment]
@davehunt I took a quick look at this and I do have a bunch of questions, plus there are some things I don't understand. Can we discuss this PR in our meeting on Wednesday?

**Comment by davehunt** [comment]
> Can we discuss this PR in our meeting on Wednesday?

Of course. I look forward to it. :smile:

**Comment by davehunt** [comment]
@bobsilverberg I've updated this with error handling for the cloud provider API calls as we discussed. Sorry for the delay. r?

**Comment by davehunt** [comment]
Merged.

**Pull request closed without merging**
